### PR TITLE
Support file_prefix for calc

### PR DESCRIPTION
**Pull request by palkan**
It could also be useful to generate a simple output for the specified path.

### CODE REVIEW

**Comment by julianrubisch** [comment]
Great! Would you mind updating the readme section for that, too?

**Comment by palkan** [comment]
> Would you mind updating the readme section for that, too?

Done!

**Comment by julianrubisch** [comment]
Oh, please submit an updated Gemfile.lock. The CI build seems to complain about that... then I can merge

**Comment by palkan** [comment]
> please submit an updated Gemfile.lock

I haven't changed it.

Btw, you shouldn't keep`.lock` files in the repo for gems, CI should rely only on the requirements described in the `.gemspec` (and that's, probably, why it fails—some dependency has been updated and `Gemfile.lock` is not; but we should not care about it).

**Comment by julianrubisch** [comment]
You‘re right. Will patch that later

**Comment by palkan** [comment]
@julianrubisch Please, ping me as soon as this will be released. Thanks!

**Comment by julianrubisch** [comment]
ping ;-)

**Comment by palkan** [comment]
Thanks!

**Pull request merged**
