### PR TITLE
Check for StandardRB offenses in CI

### PR DESCRIPTION
**Pull request by mtancoigne**
Hello !

I see there is Rubocop in the project, but it's not used in CI.

This PR adds a Github action to enable it, if you're interested... (and there will be a lot of files to lint :)

### CODE REVIEW

**Comment by julianrubisch** [comment]
Hey! Ugh sorry, I wish you'd have asked me before, just yesterday I came to the conclusion to use `standardrb` for this... it's actually in the project as a development dependency already, so you could just change that to something like this?

```yml
    - name: Run StandardRB
      run: bundle exec standardrb --format progress
```

**Comment by mtancoigne** [comment]
Of course !

**Comment by julianrubisch** [comment]
Thanks a ton! Now I've yet got to find out why Github Actions insists on running checks that aren't there anymore, and doesn't run new checks 😴

**Comment by mtancoigne** [comment]
Should I remove Rubocop-related stuff too ?

**Comment by mtancoigne** [comment]
I added e25bb22f92af24f8546d60bfc9794c4d7194c34b in, as it fixes StandardRB offenses
```text
standard: Use Ruby Standard Style (https://github.com/testdouble/standard)
  lib/attractor/cli.rb:57:11: Style/IdenticalConditionalBranches: Move `Attractor::HtmlReporter.new(file_prefix: file_prefix, calculators: calculators(options), open_browser: open_browser).report` out of the conditional.
  lib/attractor/cli.rb:59:11: Style/IdenticalConditionalBranches: Move `Attractor::HtmlReporter.new(file_prefix: file_prefix, calculators: calculators(options), open_browser: open_browser).report` out of the conditional.
  lib/attractor/cli.rb:79:11: Style/IdenticalConditionalBranches: Move `Attractor::SinatraReporter.new(file_prefix: file_prefix, calculators: calculators(options), open_browser: open_browser).report` out of the conditional.
  lib/attractor/cli.rb:81:11: Style/IdenticalConditionalBranches: Move `Attractor::SinatraReporter.new(file_prefix: file_prefix, calculators: calculators(options), open_browser: open_browser).report` out of the conditional.
```

**Comment by julianrubisch** [comment]
You're a beast, thanks!

**Comment by julianrubisch** [comment]
I'll maybe have time to look at your PRs this afternoon, can't guarantee it though...

**Comment by julianrubisch** [comment]
I took the liberty and fixed some CI issues in #97

**Pull request merged**
