### PR TITLE
README updates

### PR DESCRIPTION
**Pull request by andrewmcodes**
Add some updates to the README.

Possibly went a little overboard with the link extraction..

Also - I think you should take a look at the `Development` section. I know that's bundler boilerplate but I think it would be worth filling that out if you're are looking for contributors.

### CODE REVIEW

**Comment by julianrubisch** [comment]
I like this a lot! 

We should probably make the breaking changes stand out a little more and ultimately link to the v1 (I already created the branch)

**Comment by andrewmcodes** [comment]
@julianrubisch if there are breaking changes- I assume you are bumping to v2?

**Comment by julianrubisch** [comment]
Exactly

**Comment by andrewmcodes** [comment]
@julianrubisch is including that information in the release notes not enough?

**Comment by julianrubisch** [comment]
🤨 I‘d probably still write a note ...

**Comment by andrewmcodes** [comment]
@julianrubisch would you mind adding this change or letting me know what it should be?

**Comment by julianrubisch** [comment]
All 👌🏻, I just need to pull myself together and release it

**Pull request merged**
